Cleanup of package maintainer scripts

diff --git a/package/pivccu-modules-dkms/postinst b/package/pivccu-modules-dkms/postinst
--- a/package/pivccu-modules-dkms/postinst
+++ b/package/pivccu-modules-dkms/postinst
@@ -1,6 +1,7 @@
-set -e
+#!/bin/bash
+. /usr/share/debconf/confmodule
 
-systemctl enable pivccu-dkms.service
+set -e
 
 DKMS_NAME=pivccu
 DKMS_PACKAGE_NAME=$DKMS_NAME-dkms
@@ -9,20 +10,32 @@ DKMS_VERSION={PKG_VERSION}
 postinst_found=0
 
 case "$1" in
-        configure)
-                for DKMS_POSTINST in /usr/lib/dkms/common.postinst /usr/share/$DKMS_PACKAGE_NAME/postinst; do
-                        if [ -f $DKMS_POSTINST ]; then
-                                $DKMS_POSTINST $DKMS_NAME $DKMS_VERSION /usr/share/$DKMS_PACKAGE_NAME "" $2
-                                postinst_found=1
-                                break
-                        fi
-                done
-                if [ "$postinst_found" -eq 0 ]; then
-                        echo "ERROR: DKMS version is too old and $DKMS_PACKAGE_NAME was not"
-                        echo "built with legacy DKMS support."
-                        echo "You must either rebuild $DKMS_PACKAGE_NAME with legacy postinst"
-                        echo "support or upgrade DKMS to a more current version."
-                        exit 1
-                fi
-        ;;
+  configure)
+    for DKMS_POSTINST in /usr/lib/dkms/common.postinst /usr/share/$DKMS_PACKAGE_NAME/postinst; do
+      if [ -f $DKMS_POSTINST ]; then
+        $DKMS_POSTINST $DKMS_NAME $DKMS_VERSION /usr/share/$DKMS_PACKAGE_NAME "" $2
+        postinst_found=1
+        break
+      fi
+    done
+
+    if [ "$postinst_found" -eq 0 ]; then
+      echo "ERROR: DKMS version is too old and $DKMS_PACKAGE_NAME was not"
+      echo "built with legacy DKMS support."
+      echo "You must either rebuild $DKMS_PACKAGE_NAME with legacy postinst"
+      echo "support or upgrade DKMS to a more current version."
+      exit 1
+    fi
+
+    systemctl enable pivccu-dkms.service
+
+    if [ -z "$2" ]; then
+      db_fset pivccu/reboot_required seen false
+      db_input medium pivccu/reboot_required || true
+      db_go
+    fi
+    ;;
+
+  abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
 esac
